resolver: lts-6.23
packages:
  - '.'
  - location:
      git: https://cocreature@bitbucket.org/cocreature/pipes-shell.git
      commit: 24ec1e5e2b7479ff0bd57c0f5fcdd70c57ad9851
    extra-dep: true
extra-deps:
  - posix-paths-0.2.1.0
  - pipes-files-0.1.1
  - hierarchy-0.3.1
flags: {}
extra-package-dbs: []
