resource_types:
- name: rsync-resource
  type: docker-image
  source:
      repository: mrsixw/concourse-rsync-resource
      tag: latest
resources:
- name: llreve-git
  type: git
  source:
    uri: https://github.com/mattulbrich/llreve.git
- name: llreve-static-binary-host
  type: rsync-resource
  source:
    server: {{llreve-static-host}}
    port: {{llreve-static-host-port}}
    base_dir: /var/www/html/downloads
    user : root
    private_key: {{private-key}}
    disable_version_path: true
jobs:
- name: llreve-static
  serial: true
  plan:
  - get: llreve-git
    trigger: true
  - task: llreve-build-static
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cocreature/llreve
          tag: llvm-3.9_z3-4.5
      inputs:
        - name: llreve-git
      outputs:
        - name: static-binaries
      run:
        path: llreve-git/concourse/build.sh
  - put: llreve-static-binary-host
    params:
      sync_dir: static-binaries
