resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
resources:
- name: llreve
  type: git
  source:
    branch: concourse
    uri: https://github.com/mattulbrich/llreve.git
- name: gcs
  type: gcs-resource
  source:
    bucket: llreve
    json_key: {{gcs-json}}
    regexp: llreve-(.*)
jobs:
- name: llreve-static
  plan:
  - get: llreve
    trigger: true
  - put: gcs
    params:
      file: "static-binaries/llreve-*"
      predefined_acl: publicRead
  - task: llreve-build-static
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cocreature/llreve
          tag: llvm-3.9_z3-4.5
      inputs:
        - name: llreve
      outputs:
        - name: static-binaries
      run:
        path: llreve/concourse/build.sh
