ignored-dirs:
  - ignored
  - notyetworking
  - discuss
  - coreutils
  - linux
  - torch
ignored-files:
  - a_1.c
  - heap/selsort_1.c
  - heap/findmax_1.c
  - heap/fib_1.c
  - argon2/fill_memory_blocks_1.c
z3-files:
  - rec/add-horn.smt2
  - rec/rec_while.smt2
  - rec/cocome1.smt2
  - rec/triangular.smt2
custom-args:
  rec/rec_while.smt2: []
  rec/cocome1.smt2:
    - -only-rec
  git/swap.smt2:
    - -stack
  redis/undoconnect.smt2:
    - -fun
    - undoconnectWithMaster
  argon2/finalize.smt2:
    - -signed
  libc/memmem_1.smt2:
    - -heap
  libc/sbrk_1.smt2:
    - -signed
