ignored-dirs:
  - ignored
  - notyetworking
  - discuss
  - coreutils
  - redis
  - git
  - linux
  - torch
ignored-files:
  - a_1.c
  - heap/selsort_1.c
  - heap/findmax_1.c
  - heap/fib_1.c
  - argon2/fill_memory_blocks_1.c
z3-files:
  - rec/add-horn.smt2
  - rec/rec_while.smt2
  - rec/cocome1.smt2
  - rec/triangular.smt2
custom-args:
  rec/rec_while.smt2: []
